/**
 * Registry of completed / continuable nested agents.
 *
 * Enables Claude Code SendMessage-style continuation: after an agent finishes,
 * the parent can send a follow-up that resumes with the full prior transcript
 * (not a fresh spawn).
 *
 * Sessions live in memory (capped) and are also persisted, best-effort, to
 * .reagent/agent-sessions/<agent_id>.json so that send_message / continueAgent
 * survive a ReAgent restart. Disk sessions are loaded lazily on lookup and
 * files older than 7 days are removed on first access to each state dir.
 */

import fs from "node:fs";
import path from "node:path";

import { config } from "../config.js";
import { getLogger } from "../logs.js";
import type { ChatMessage } from "../types.js";

const log = getLogger("agents.sessions");

export interface AgentSession {
  id: string;
  agentType: string;
  title: string;
  messages: ChatMessage[];
  allowedTools: ReadonlySet<string>;
  maxSteps: number;
  forceSummary: string;
  emptyResult: string;
  doomStyle: "main" | "worker" | "none";
  /** Last reported status for list/diagnostics. */
  status: "completed" | "failed" | "running";
  updatedAt: number;
}

/** JSON-safe shape written to disk (allowedTools as array). */
interface PersistedAgentSession extends Omit<AgentSession, "allowedTools"> {
  allowedTools: string[];
}

const sessions = new Map<string, AgentSession>();

/** Cap retained sessions to bound memory (oldest evicted). */
const MAX_SESSIONS = 32;

/** Persisted files older than this are removed on first access. */
const RETENTION_MS = 7 * 24 * 60 * 60 * 1000;

/** Ids are generated by newAgentSessionId; reject anything path-unsafe. */
const SAFE_ID = /^[A-Za-z0-9._-]+$/;

function sessionsDir(): string {
  return path.join(config.stateDir, "agent-sessions");
}

// --- retention -------------------------------------------------------------

const lastSweptAt = new Map<string, number>();
/** Re-check retention at most this often per dir, so a long-running `serve`
 * process doesn't accumulate persisted sessions forever after its first sweep. */
const SWEEP_INTERVAL_MS = 60 * 60 * 1000;

/** Removes persisted sessions older than RETENTION_MS (at most once per SWEEP_INTERVAL_MS per dir). */
function sweepOldSessions(dir: string): void {
  const now = Date.now();
  const last = lastSweptAt.get(dir);
  if (last !== undefined && now - last < SWEEP_INTERVAL_MS) return;
  lastSweptAt.set(dir, now);
  let files: string[];
  try {
    files = fs.readdirSync(dir);
  } catch {
    return;
  }
  const cutoff = now - RETENTION_MS;
  for (const file of files) {
    if (!file.endsWith(".json")) continue;
    const full = path.join(dir, file);
    try {
      if (fs.statSync(full).mtimeMs < cutoff) fs.unlinkSync(full);
    } catch {
      // best-effort
    }
  }
}

// --- disk I/O (best-effort: must never break the turn) ----------------------

/** Atomic (tmp+rename) best-effort write of a session to disk. */
function persistSession(session: AgentSession): void {
  if (!SAFE_ID.test(session.id)) return;
  const dir = sessionsDir();
  sweepOldSessions(dir);
  const data: PersistedAgentSession = {
    ...session,
    allowedTools: [...session.allowedTools],
  };
  const file = path.join(dir, `${session.id}.json`);
  const tmp = `${file}.tmp-${process.pid}`;
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(tmp, JSON.stringify(data), "utf8");
    fs.renameSync(tmp, file);
  } catch (e) {
    log.warning("failed to persist agent session %s: %s", session.id, String(e));
    try {
      fs.unlinkSync(tmp);
    } catch {
      // already gone
    }
  }
}

function loadSessionFromDisk(id: string): AgentSession | undefined {
  if (!SAFE_ID.test(id)) return undefined;
  const dir = sessionsDir();
  sweepOldSessions(dir);
  try {
    const raw = fs.readFileSync(path.join(dir, `${id}.json`), "utf8");
    const data = JSON.parse(raw) as PersistedAgentSession;
    if (!data || typeof data !== "object" || !Array.isArray(data.messages)) return undefined;
    return {
      ...data,
      id,
      allowedTools: new Set(Array.isArray(data.allowedTools) ? data.allowedTools : []),
    };
  } catch {
    return undefined;
  }
}

// --- registry ---------------------------------------------------------------

export function registerAgentSession(session: AgentSession): void {
  sessions.set(session.id, session);
  persistSession(session);
  if (sessions.size <= MAX_SESSIONS) return;
  const oldest = [...sessions.entries()].sort((a, b) => a[1].updatedAt - b[1].updatedAt)[0];
  if (oldest) sessions.delete(oldest[0]);
}

/** Memory first; falls back to the persisted copy (survives restarts). */
export function getAgentSession(id: string): AgentSession | undefined {
  const inMemory = sessions.get(id);
  if (inMemory) return inMemory;
  const fromDisk = loadSessionFromDisk(id);
  if (fromDisk) {
    sessions.set(id, fromDisk);
    if (sessions.size > MAX_SESSIONS) {
      const oldest = [...sessions.entries()].sort((a, b) => a[1].updatedAt - b[1].updatedAt)[0];
      if (oldest) sessions.delete(oldest[0]);
    }
  }
  return sessions.get(id) ?? fromDisk;
}

/** All known sessions: in-memory plus persisted ones from prior runs. */
export function listAgentSessions(): AgentSession[] {
  const dir = sessionsDir();
  sweepOldSessions(dir);
  const all = new Map<string, AgentSession>();
  let files: string[] = [];
  try {
    files = fs.readdirSync(dir).filter((f) => f.endsWith(".json"));
  } catch {
    // no persisted sessions
  }
  for (const file of files) {
    const id = file.slice(0, -".json".length);
    if (sessions.has(id)) continue;
    const loaded = loadSessionFromDisk(id);
    if (loaded) all.set(id, loaded);
  }
  for (const [id, session] of sessions) all.set(id, session);
  return [...all.values()].sort((a, b) => b.updatedAt - a.updatedAt);
}

/** Test / /clear helper (memory only; persisted copies remain). */
export function clearAgentSessions(): void {
  sessions.clear();
}

export function newAgentSessionId(): string {
  return `agent-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}
